/**
 * Generate .wrangler/seed/organizations.seed.sql from the legacy Excel
 * registry, using the SAME parse + normalize code path the production import
 * uses (dogfooding: if the seed works, the import works).
 *
 * Output is written under `.wrangler/` (gitignored) on purpose: the generated
 * SQL contains the full registry (PII + bank accounts) and must never be
 * committed. For a real deployment, migrate through the import API instead.
 *
 * Usage:
 *   npm run seed -- [path/to/file.xlsx]
 *
 * Output:
 *   .wrangler/seed/organizations.seed.sql  — one INSERT per row
 *   .wrangler/seed/seed-stats.json         — normalization coverage report
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as XLSX from 'xlsx';
import { parseWorkbook } from '../src/services/importer';
import { normalizeOrg } from '../src/lib/normalize-org';
import { sqlEscape } from '../src/db';
import { NIGERIAN_STATES, PROJECT_CATEGORIES } from '../src/lib/normalize';

const here = dirname(fileURLToPath(import.meta.url));
const xlsxPath = process.argv[2] ?? join(here, '..', '..', 'SAMBET GRASSROOT PROJECT 1.xlsx');

async function main() {
  console.log(`Reading ${xlsxPath}`);
  const buf = await readFile(xlsxPath);
  const parsed = await parseWorkbook(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength), xlsxPath.split('/').pop() ?? 'file.xlsx');
  console.log(`Parsed ${parsed.rows.length} data rows`);
  console.log(`Headers mapped: ${parsed.headers.join(', ')}`);
  if (parsed.unmappedHeaders.length) console.log(`Unmapped headers (ignored): ${parsed.unmappedHeaders.join(', ')}`);

  const statements: string[] = [];
  const fatalErrors = parsed.rows.filter((r) => r.error).length;
  const stats = {
    totalRows: parsed.rows.length,
    fatalErrors,
    categoryDistribution: {} as Record<string, number>,
    stateDistribution: {} as Record<string, number>,
    unrecognizedStates: {} as Record<string, number>,
    unrecognizedBanks: {} as Record<string, number>,
    phoneUnnormalized: 0,
    emailInvalid: 0,
  };
  const seenSn = new Set<number>();

  const fatalRows: number[] = [];
  for (const row of parsed.rows) {
    if (row.error) {
      fatalRows.push(row.excelRow);
      continue;
    }
    const n = normalizeOrg(row.data);
    if (n.sn != null && seenSn.has(n.sn)) {
      console.warn(`  row ${row.excelRow}: duplicate S/N ${n.sn} — S/N set to NULL to preserve the record`);
      (n as { sn: number | null }).sn = null;
    } else if (n.sn != null) {
      seenSn.add(n.sn);
    }
    for (const w of row.warnings) {
      if (w.startsWith('Unrecognized state')) {
        const raw = w.match(/“(.+)”/)?.[1] ?? '?';
        stats.unrecognizedStates[raw] = (stats.unrecognizedStates[raw] ?? 0) + 1;
      } else if (w.startsWith('Unrecognized bank')) {
        const raw = w.match(/“(.+)”/)?.[1] ?? '?';
        stats.unrecognizedBanks[raw] = (stats.unrecognizedBanks[raw] ?? 0) + 1;
      } else if (w === 'Phone number could not be normalized') stats.phoneUnnormalized++;
      else if (w === 'E-mail address looks invalid') stats.emailInvalid++;
    }
    stats.categoryDistribution[n.project_category] = (stats.categoryDistribution[n.project_category] ?? 0) + 1;
    stats.stateDistribution[n.state_norm ?? '(unknown)'] = (stats.stateDistribution[n.state_norm ?? '(unknown)'] ?? 0) + 1;

    const lit = (v: string | number | null) => (v === null ? 'NULL' : typeof v === 'number' ? String(v) : `'${sqlEscape(v)}'`);
    statements.push(
      `INSERT INTO organizations (sn, name, ceo_name, phone, email, bank, bank_norm, account_number, lga, state, state_norm, project_type, project_category, status, notes, cycle, source) VALUES (${[
        lit(n.sn), lit(n.name), lit(n.ceo_name), lit(n.phone), lit(n.email), lit(n.bank), lit(n.bank_norm),
        lit(n.account_number), lit(n.lga), lit(n.state), lit(n.state_norm), lit(n.project_type),
        lit(n.project_category), lit(n.status), lit(n.notes), lit(n.cycle), `'import'`,
      ].join(', ')});`,
    );
  }

  const outDir = join(here, '..', '.wrangler', 'seed');
  await mkdir(outDir, { recursive: true });
  // No explicit BEGIN/COMMIT: `wrangler d1 execute` rejects SQL-level
  // transactions (it manages them itself / recommends the JS API).
  const sql = [
    '-- Generated by scripts/generate-seed.ts from the legacy Excel registry.',
    '-- Do not edit by hand or commit. Re-run: npm run seed -- <file.xlsx>',
    ...statements,
  ].join('\n');
  await writeFile(join(outDir, 'organizations.seed.sql'), sql);
  await writeFile(join(outDir, 'seed-stats.json'), JSON.stringify(stats, null, 2));

  if (fatalRows.length) {
    console.warn(`\n${fatalRows.length} rows skipped (fatal): rows ${fatalRows.slice(0, 8).join(', ')}${fatalRows.length > 8 ? ` … (+${fatalRows.length - 8} more)` : ''}`);
  }
  console.log(`\nWrote ${statements.length} INSERTs to .wrangler/seed/organizations.seed.sql (gitignored)`);
  console.log('\n=== Normalization coverage ===');
  console.log('Categories:', stats.categoryDistribution);
  const knownStates = NIGERIAN_STATES.length;
  const unknownStateEntries = Object.entries(stats.unrecognizedStates);
  console.log(`States: ${Object.keys(stats.stateDistribution).length - 1}/${knownStates} canonical states used; ${unknownStateEntries.length} unrecognized variants`);
  for (const [k, v] of unknownStateEntries) console.log(`   unrecognized state: ${v}x "${k}"`);
  const unknownBankEntries = Object.entries(stats.unrecognizedBanks).sort((a, b) => b[1] - a[1]);
  console.log(`Banks: ${unknownBankEntries.length} unrecognized variants (top 15):`);
  for (const [k, v] of unknownBankEntries.slice(0, 15)) console.log(`   unrecognized bank: ${v}x "${k}"`);
  console.log(`Phones not normalizable: ${stats.phoneUnnormalized}`);
  console.log(`E-mails flagged invalid: ${stats.emailInvalid}`);
  console.log(`All categories present:`, PROJECT_CATEGORIES.filter((c) => stats.categoryDistribution[c]).join(', '));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
